создал класс User
MaximSlepukhin/java-filmorate pull request #5
Opened 2024-01-04 08:55 UTC by MaximSlepukhin

2024-01-09 19:28 UTC, dgumich requested changes

2024-01-09 19:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/annotations/HistoricalReleaseDateValidator.java
> +        Field[] fields = obj.getClass().getDeclaredFields();
Воу воу, молодец, что затронул рефлексию. На ней, между прочим, многое в спринге построено. Но зачем нам это? Код должен быть простой, если он может быть таким=)
Молодец, что даже сделал свою аннотацию для фильма. Но что нам нужно проверить? Только одно поле у фильма. И для этого пишем аннотацию+кастомный валидатор, который работает через рефлекшн, только для того что бы проверить поле, которые мы знаем как называется?=) Ту мач эффортс для такой задачи.
Упрости: даже если оставить валидатор, то можно в данном методе просто проверять значение даты у фильма и все.

2024-01-09 19:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/annotations/HistoricalReleaseDateValidator.java
> +                    throw new IllegalArgumentException("Release date must not be before " + annotation.value());
У нас же есть свое кастомное исключение для случаев ошибки валидации. Тут как раз такая ошибка, так что логично использовать его, а не IllegalArgumentException

2024-01-09 19:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Старайся писать код в одном стиле. Если используешь ломбок для создания логгера как в FilmController, то используй его и здесь. Или наоборот не используй его нигде и создавай сам

2024-01-09 19:28 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.debug("Получен запрос POST /user");
Логичней перенести логирование перед проверкой имени/даты рождения, потому что мы можем кинуть исключение и до логгирования так и не дойдем.

2024-01-10 17:29 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Исправил.

2024-01-11 21:46 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.debug("Получен запрос POST /user");
Согласен. Перенес логирование перед проверкой.

2024-01-11 21:46 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/annotations/HistoricalReleaseDateValidator.java
> +                    throw new IllegalArgumentException("Release date must not be before " + annotation.value());
Исправил.

2024-01-11 21:46 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/annotations/HistoricalReleaseDateValidator.java
> +        Field[] fields = obj.getClass().getDeclaredFields();
Согласен. Исправил.

2024-01-11 21:52 UTC, merged