Add friends likes
MaximSlepukhin/java-filmorate pull request #7
Opened 2024-01-21 18:10 UTC by MaximSlepukhin

2024-01-22 02:18 UTC, dgumich requested changes

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(MIN_DATE_RELEASE)) {
Валидация должна быть в сервисном слое. Контроллер вызывает сервисный слой, там фильм валидируется, если все ок -> вызывается сторедж (из сервисного слоя) и сохраняется фильм.

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.postFilm(film);
Здесь должен быть вызов сервиса, а не стореджа.

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.updateFilm(film);
Аналогично, должны работать с сервисом, а не стореджем.

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void like(@PathVariable Integer id, @PathVariable Integer userId) {
Не правильное название метода. Забыл как давать имена методам?=) глагол+существительное. Тут или глагол или существительное.=)

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getFilms();
Тут тоже должен вызываться сервис

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping(value = {"popular?count={count}", "popular"})
Необычный подход=) Все проще, в @GetMapping просто указываешь путь (без параметром, только popular), а необходимый параметр спринг сам тебе достанет https://www.baeldung.com/spring-request-param

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Здесь так же не должно быть стореджа, контроллер работает с сервисом

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Integer idOfUser = userService.findUserById(userId).getId();
А это что за логика?=) У нас есть айди, по нему мы находим пользователя и берем его айди, которое будет таким же как это самое айди. Зачем? То что надо проверить так это наличие пользователя с таким айди.

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Integer idOfUser = userService.findUserById(userId).getId();
Аналогично, зачем так делаем?=)

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> film = films.stream()
А это нам зачем?) Не проще ли в сторедже создать метод getFilmById, который и будет возвращать фильм по айди? Это же легко сделать=)

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film getFilmById(Integer id) {
А зачем нам этот метод, когда уже есть findFilmById(Integer id)? в чем принципиальное отличие, кроме наличия проверки?

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public final FilmStorage filmStorage;
Поля должны быть приватными

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Лишная пустая строка

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.userStorage = userStorage;
А зачем нам юзер сторедж? Где мы его используем?

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public final UserStorage userStorage;
Поля должны быть приватными

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Set<User> friendsList(Integer id) {
Не правильно название метода. Что значит список друзей? Получить? Удалить? Обновить?

2024-01-22 02:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> listOfCommonFriends(Integer id, Integer otherId) {
Аналогично, забыл про то как давать названия методам=(

2024-01-22 20:15 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Понял. Исправил.

2024-01-22 20:19 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.postFilm(film);
Исправил.

2024-01-22 20:23 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.updateFilm(film);
Исправил.

2024-01-22 20:28 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void like(@PathVariable Integer id, @PathVariable Integer userId) {
Заменил название метода "like" на "addLike".

2024-01-24 22:33 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler
Попытался так сделать. В итоге программа выдала Error. Пытался разобраться - потратил кое-какое время, так и не понял с чем была связана ошибка. Пока оставил как было.

2024-01-24 22:33 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(MIN_DATE_RELEASE)) {
Исправил.

2024-01-24 22:35 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping(value = {"popular?count={count}", "popular"})
Пока оставил как есть. Комментарий ваш понял. Если не ошибаюсь, тоже на этом ресурсе смотрел запись.

2024-01-24 22:35 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Исправил.

2024-01-24 22:41 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Integer idOfUser = userService.findUserById(userId).getId();
Логики нет=) что то в процессе делал, да не проверил.
Исправил.

2024-01-24 22:42 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Integer idOfUser = userService.findUserById(userId).getId();
Исправил.

2024-01-24 22:48 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film getFilmById(Integer id) {
Согласен. Убрал. Не проверил.

2024-01-24 22:50 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public final FilmStorage filmStorage;
Исправил.

2024-01-24 22:50 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Исправил.

2024-01-24 22:52 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.userStorage = userStorage;
Согласен. Невнимательность.

2024-01-24 22:52 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public final UserStorage userStorage;
Исправил.

2024-01-24 22:55 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Set<User> friendsList(Integer id) {
Заменил на "getListOfFriends". Согласен.

2024-01-24 22:57 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> listOfCommonFriends(Integer id, Integer otherId) {
Заменил на "getListOfCommonFriends".

2024-01-25 04:02 UTC, dgumich requested changes

2024-01-25 04:02 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        checkId(id);
А зачем делать такой велосипед? Надо только добавить метод в сторедж findUserById, который по айди будет возвращать юзера из мапы и все. Если есть - вернет, если нет - то вернет null. Не надо усложнять то, что можно сделать просто=)

2024-02-07 19:44 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public final Integer topfilm = 10;
Исправил.

2024-02-07 19:45 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      @Valid
Исправил.

2024-02-07 19:45 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    /*public Film getFilmById(Integer id) {
Удалил.

2024-02-07 19:47 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User userOne = findUserById(id);
Согласен. Исправил.

2024-02-07 19:51 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final LocalDate MIN_DATE_RELEASE = LocalDate.of(1895, 12, 28);
Исправил.

2024-02-07 19:52 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    Integer count = 0;
Исправил

2024-02-07 19:55 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void checkId(Integer id) {
Исправил.

2024-02-07 20:34 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping(value = {"popular?count={count}", "popular"})
Исправил.

2024-02-07 20:50 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> film = films.stream()
Исправил.

2024-02-07 21:06 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        checkId(id);
Исправил.

2024-02-07 21:38 UTC, MaximSlepukhin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Что-то пошло не так");
Исправил.

2024-02-08 02:42 UTC, dgumich approved these changes

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Запрос на добавление фильма принят.");
Хорошо бы давать какую-то информацию по фильму. А то представь: у тебя отправилось 100 запросов на создание фильма, 10 фильмов не создалось, а в логах 95 таких записей. Вот как понять какой запрос вообще не пришел (потерялся по пути), а какой пришел, но мы не отработали? Поэтому хотя бы название фильма стоит добавить

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Запрос на обновление фильма принят.");
Аналогично и здесь, хорошо бы добавить какую-нибудь информацию про фильм

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> topFilms(@RequestParam(defaultValue = "10") Integer count) {
Вот, молодец, на много же удобней=)

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.createUser(user);
Ай ай ай, пропущенный комментарий=)

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
Надеюсь, что понимаешь, что за "магия" скрывается за аннотацией  @Autowired =)

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Slf4j
Если мы не логируем, то зачем нам логер?=)

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        Collection<Film> films = getFilms();
Что это такое????=) У тебя есть айди, есть мапа, в которой по этому айди лежит фильм. Делаешь  films.get(id)  и все.

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Map<Integer, Film> films = new HashMap<>();
Мапа должна быть приватной

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStrorage.java
> +    public Map<Integer, User> users = new TreeMap<>();
Мапа должна быть приватной

2024-02-08 02:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStrorage.java
> +        Collection<User> users = getUsers();
Аналогично, зачем нам такая сложная логика, если можем просто взять из мапы по id?

2024-02-26 22:55 UTC, merged